---
name: idr0067-king-yeastmeiois/experimentA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: no
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split: ;
  # Should this column be included in the clients (yes/no)
  includeclient: yes
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: yes
  # Should empty values be omitted from the client display
  omitempty: yes

columns:

  - name: Protocol
    clientname: Protocol
    include: yes
  - name: Comment [Genetic Background]
    clientname: Genetic Background
    include: yes
  - name: Comment [Genetic Background Identifier]
    clientname: Genetic Background Identifier
    include: yes
  - name: Comment [Construct\Marker] 1
    clientname: Construct/Marker
    include: yes
  - name: Experimental Condition [Imaging Type]
    clientname: Imaging Type
    include: yes
  - name: Channels
    clientname: Channels
    include: yes
  - name: Comment [Image File Type]
    clientname: Image File Type
    include: yes
  - name: Comment [Experimental Conclusion]
    clientname: Experimental Conclusion
    include: yes

  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier] 1
          clientname: Gene Identifier
          include: yes
        - name: Comment [Gene Identifier] 1
          clientname: Gene Identifier URL
          clientvalue: http://www.yeastgenome.org/locus/{{ value|urlencode }}
          include: yes
        - name: Comment [Gene Symbol] 1
          clientname: Gene Symbol
          include: yes
  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier] 2
          clientname: Gene Identifier
          include: yes
        - name: Comment [Gene Identifier] 2
          clientname: Gene Identifier URL
          clientvalue: http://www.yeastgenome.org/locus/{{ value|urlencode }}
          include: yes
        - name: Comment [Gene Symbol] 2
          clientname: Gene Symbol
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
        - name: Characteristics [Cell Line]
          clientname: Cell Line
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/protein
      columns:
        - name: Comment [Protein] 1
          clientname: Protein
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/protein
      columns:
        - name: Comment [Protein] 2
          clientname: Protein
          include: yes

advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/gene
      keys:
        - Gene Identifier
        - Gene Symbol
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
        - Cell Line
    - namespace: openmicroscopy.org/mapr/protein
      keys:
        - Protein
